config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :corsaires



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsaire.rb
class Corsaire < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/corsaires_controller.rb
class CorsairesController < ApplicationController
  def new
  	@corsaire = Corsaire.new
  end

  def create
  	corsaire = Corsaire.create(corsaire_params)
  	redirect_to corsaire_path(corsaire.id)
  end


  def show
    @corsaire = Corsaire.find(params[:id])
  end

  def edit
    @corsaire = Corsaire.find(params[:id])
    #redirect_to corsaire_path(@corsaire.id)
    #esto no funciona, ya que inmediatamente me lleva a corsaire_path osea, show, y nunca llego a edit-nosense
  end

  def update
    @corsaire = Corsaire.find(params[:id])
    @corsaire.update(corsaire_params)
    redirect_to corsaires_path(@corsaire.id) #redirecting to INDEX (grafikart) otherwise to show->corsaire_path

  end

  def index
    @corsaire = Corsaire.all #creo que este es el que le envía a  la página index la info
  end

  def destroy
    @corsaire = Corsaire.find(params[:id])
    @corsaire.destroy
    redirect_to corsaires_path(@corsaire.id) #redirect to index
  end

  def corsaire_params
    params.require(:corsaire).permit(:first_name, :age)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corsaires_helper.rb
module CorsairesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/corsaires/edit.html.erb
<h1>Edit <%= @corsaire.first_name %> </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@corsaire) do |f| %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :age %>
      <%= f.text_field :age %>

      <%= f.submit "Modify", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/corsaires/index.html.erb
<h1>Corsaires</h1>
<% @corsaire.each do |each_corsaire| %>

<h3><%= each_corsaire.first_name %></h3>
<p><%= each_corsaire.age %></p>
<p>
	<a href="<%= corsaire_path(each_corsaire.id) %>" class="btn btn-primary">Know more</a>
	<a href="<%= corsaire_path(each_corsaire.id) %>" class="btn btn-danger" data-confirm="Are you sure?" data-method="DELETE">Delete</a>
</p>

<% end %>

<h3>Create New User</h3>
<a href="<%=new_corsaire_path%>" class="btn btn-success">Create a new User</a>

<!-- <%= link_to "Enregistre-toi !", new_corsaire_path, class: "btn btn-lg btn-primary" %> -->

app/views/corsaires/new.html.erb
<h1>Create New User</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@corsaire) do |f| %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: "Juan Pablo" %>

      <%= f.label :age %>
      <%= f.text_field :age, placeholder: "34" %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/corsaires/show.html.erb
<h1>Hello <%= @corsaire.first_name %></h1>
<p>You are <%= @corsaire.age %> years old</p>

<%=link_to "Edit", edit_corsaire_path, class: "btn btn-lg btn-primary"%>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",   root_path %></li>
        <li><%= link_to "Index des corsaires",   corsaires_path %></li>
        <li><%= link_to "Nouveau corsaire", new_corsaire_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FridayProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/header' %>
  <div class="thebody">
    <%= yield %>
  </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les corsaires 🎓
  </h3>
  <%= link_to "Enregistre-toi !", new_corsaire_path, class: "btn btn-lg btn-primary" %>
</div>